config/routes.rb
Rails.application.routes.draw do
  resources :messages

  root to: "messages#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

  private

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => 'https://api.twilio.com/2010-04-01/Accounts/AC33934a01b1e0ee001008569d4a8f2671/Messages.json',
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])  
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "yay"
      redirect_to messages_path
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwilioPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Textin and Stuff</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li><a href="/messages">All Messages</a></li>
          <li><a href="/messages/new">Send a Message</a></li>
        </ul>
      </div>
    </div>
  </nav>

   <div class="container main-container">
     <% if notice %>
     <p id ="flash" class="alert alert-success"><%= notice %></p>
     <% end %>
     <% if alert %>
     <p id ="flash" class="alert alert-danger"><%= alert %></p>
     <% end %>
    <%= yield %>
   </div>

   <script type="text/javascript">
     $(document).ready(function(){
       setTimeout(function(){
         $('#flash').fadeOut();
       }, 1500);
     })
   </script>
</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<% @messages.each do |message| %>
  <p>
    <%= link_to message.id, message_path(message)  %>
  </p>
<% end %>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>
    Didn't work bro
  </p>
  <% @message.errors.full_messages.each do |error| %>
    <p>
      <%= error %>
    </p>
  <% end %>
<% end %>

<%= bootstrap_form_for @message do |f| %>
  <%= f.text_field :to %>
  <%= f.text_field :from %>
  <%= f.text_field :body %>
  <%= f.submit "Create Message" %>
<% end %>

app/views/messages/show.html.erb
<h1>Message <%= @message.id %> </h1>
<p>
  From: <%= @message.from %>
</p>
<p>
  To: <%= @message.to %>
</p>
<p>
  Text: <%= @message.body %>
</p>